---
name: checks
on: [push]

jobs:
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.RECIPE_APP_TOKEN}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run -rm app sh -c "python manage.py wait_for_db && #we have to check for the availability of db before running test
                                               python manage.py test"

      - name: lint
        run: docker-compose run -rm app sh -c "flake8"
